services:
  php:
    build:
      context: ../images
      dockerfile: php.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build:
      context: ../images
      dockerfile: nginx.Dockerfile
    depends_on:
      - php
    ports:
      - "127.0.0.1:8081:80"
